import type {Song} from './music';
const ready="{comment:Intro}\n[C] | - | [Dm] | - |\n[F] | - | [G] | [C] |\n\n{comment:Chorus}\n[C]Dangakara handakari [Dm]obe kammul walata wada\nMal [F]pethi sinidu [G]na kiya mama [C]dannawa\n[C]Obe mini nil dasa wa[Dm]sa mage sitha umathu kala\nKi[F]ya...[G].   Oba [C]dannawa..//\n\n{comment:Verse 1}\nOba [F]malak wela sondu[G]ru\nMage[Am] papuwa pura piru[Em]nu\nNi[Dm]mawak nathi adare.. [G]Kawruwath danne na...\nMage diwi [Am]thibena thura.. [G]  Oba mata [F]labuna ki[G]ya..\n\n{comment:Verse 2}\n[C]\nDiwi [F]Madura pura piru[G]nu\nDew [Am]duwak wela thuru[Em]nu\nNi[Dm]mawak nathi jeewithe..  [G]Kawruwath danne na..\nSasarin [Am]sasara sara..[G]. Oba mata [F]labuna ki[G]ya..\n\n{comment:Chorus}\n[C]Dangakara handakari [Dm]obe kammul walata wada\nMal [F]pethi sinidu [G]na kiya mama [C]dannawa\n[C]Obe mini nil dasa wa[Dm]sa mage sitha umathu kala\nKi[F]ya...[G].   Oba [C]dannawa..//\n\n{comment:Final chorus - up two semitones}\n[D]Dangakara handakari [Em]obe kammul walata wada\nMal [G]pethi sinidu [A]na kiya mama [D]dannawa\n[D]Obe mini nil dasa wa[Em]sa mage sitha umathu kala\nKi[G]ya...[A].   Oba [D]dannawa..\n\n";
const english=[['Good to Be','Mark Ambor'],['Riptide','Vance Joy'],['Shotgun','George Ezra'],['What Makes You Beautiful','One Direction'],['Love Yourself','Justin Bieber'],['Pompeii','Bastille'],['Karma Chameleon','Culture Club'],['Perfect','Ed Sheeran']];
const sinhala=['Chandrayan Pidu','Lassana Lokaye','Dangakara Hadakari','Prarthana','Kusum Latha Renu Latha','Visekari','Gum Nade','Daasa Piya Gath Kala','Oba Apple Malak Wage','Mrs. Perera','Bappage Akkage Duwa','Pandama','Aa Pawasu Loke','Unmadini','Hinahenne Mn','Baila Gamuda Remix Karala','Mango Kale Nande','Suragana Kirilliye','Sililara Sitha Nayana','Dura Akahare','Hitha Nabara Thaleta','Mata Nelaganna Bari'];
// Release titles verified against the linked artist catalog; lyrics are not imported.
const channuka=['Mandaaram Handaawe','Eka Wassak','Eka Wassak (Stripped Version)','Eka Wassak (Live with Stereo)','Orion','Orion (Acoustic Version)','Oba Maage Aadare','Tap It','Oya Hithai Mage Hithai','Oya Hithai Mage Hithai (Acoustic Version)','Oya Watha','Oya Watha (Acoustic)','Ohuge Ruwa','Ohuge Ruwa (Acoustic Version)','Denga Natuwa','Dawasak Da Raaka','Galawumkaraya','Kawrundo'];
export const catalogSource='https://www.shazam.com/artist/channuka/1599136249';
function make(title:string,artist:string,language:Song['language']):Song {return {id:title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,''),title,artist,language,key:'',content:'',source:'',transpose:0,favorite:false};}
export const SEED:Song[]=[...english.map(([t,a])=>make(t,a,'English')),...sinhala.map(t=>make(t,t==='Prarthana'?'Daddy':'','Sinhala')),...channuka.map(t=>({...make(t,'Channuka','Sinhala'),source:catalogSource}))].map(s=>s.id==='dangakara-hadakari'?{...s,key:'C',content:ready,source:'https://chordslankalk.com/song_view.php?song_id=1313',favorite:true}:s);
